--create a table to load into via APEX ; 
-- this will be able to be cross-referenced with what is in the database to QC our photoquadrat imagery and speed up optical validaiton/get it done while on the cruise

--01 create the table 
  CREATE TABLE "GISDAT"."APEX_FILESYS_PQ_SITES" 
   (	"SITE" VARCHAR2(20 BYTE), 
	"OBJECTID" NUMBER NOT NULL ENABLE, 
	"DIRECTORY_PATH" VARCHAR2(150 BYTE), 
	"FILENAME" VARCHAR2(30 BYTE), 
	"FULL_FILE_PATH" VARCHAR2(150 BYTE), 
	 CONSTRAINT "APEX_FILESYS_PQSITES_PK" PRIMARY KEY ("OBJECTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "GISDATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "GISDATA" ;

----------------------------------------------
--02 create sequence & trigger for primary key
CREATE SEQUENCE APEX_FILESYS_PQ_SITES_OBJID_SEQ

CREATE TRIGGER "APEX_FILESYS_PQ_SITES_OBJID_PK" 
BEFORE INSERT ON APEX_FILESYS_PQ_SITES FOR EACH ROW
BEGIN
	IF :NEW.OBJECTID IS NULL THEN
		SELECT APEX_FILESYS_PQ_SITES_OBJID_SEQ.Nextval INTO :NEW.OBJECTID FROM DUAL;
	END IF;
END;

COMMIT;
