-- 01 CREATE A PRIMARY KEY
CREATE SEQUENCE  "GISDAT"."SFM_METADATA_METAID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 640 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- 02 CREATE TRIGGER FOR PRIMARY KEY
CREATE TRIGGER "SFM_METADATA_METAID_PK" 
BEFORE INSERT ON SFM_METADATA FOR EACH ROW
BEGIN
	IF :NEW.SFMMETAID IS NULL THEN
		SELECT SFM_METADATA_METAID_SEQ.Nextval INTO :NEW.SFMMETAID FROM DUAL;
	END IF;
END;

-- 03 CREATE A UNIQUE KEY
CREATE SEQUENCE SFM_METADATA_OBJID_SEQ;

-- 04 ADD A TRIGGER TO POPULATE THE UNIQUE KEY
CREATE TRIGGER "SFM_METADATA_OBJID_PK" 
BEFORE INSERT ON SFM_METADATA FOR EACH ROW
BEGIN
	IF :NEW.OBJECTID IS NULL THEN
		SELECT SFM_METADATA_OBJID_SEQ.Nextval INTO :NEW.OBJECTID FROM DUAL;
	END IF;
END;


-- 05 SET CONSTRAINTS ON THE DATABASE TABLE SFM_METADATA : PRIMARY KEY AS SFMMETAID, UNIQUE KEY AS OBJECTID, FOREIGN KEY AS SITE_VISIT.SITEVISITID
