CREATE SEQUENCE SFM_METADATA_OBJID_SEQ;

CREATE TRIGGER "SFM_METADATA_OBJID_PK" 
BEFORE INSERT ON SFM_METADATA FOR EACH ROW
BEGIN
	IF :NEW.OBJECTID IS NULL THEN
		SELECT SFM_METADATA_OBJID_SEQ.Nextval INTO :NEW.OBJECTID FROM DUAL;
	END IF;
END;
